GRANT USAGE ON SCHEMA public TO :"api_user";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO :"api_user";

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO :"api_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"migrator_user"
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO :"api_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"migrator_user"
IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES TO :"api_user";
