FROM pgscope-oracle-collector:0.3.0

USER root

RUN sed -i \
    's/s\.parsing_schema_name AS parsing_schema/CAST(NULL AS VARCHAR2(128)) AS parsing_schema/' \
    /app/oracle_collector.py \
    && sed -z -i \
    's/instance\.get(\n                "database_name"\n            )\n            or target\["database_name"\]/target["database_name"]/g' \
    /app/oracle_collector.py

USER 100
