apiVersion: v1
kind: ConfigMap
metadata:
  name: pgscope-migrations

data:
  001_schema.sql: |
{{ .Files.Get "migrations/001_schema.sql" | indent 4 }}

  002_auth_first_login.sql: |
{{ .Files.Get "migrations/002_auth_first_login.sql" | indent 4 }}

  003_storage_grants.sql: |
{{ .Files.Get "migrations/003_storage_grants.sql" | indent 4 }}

  004_api_grants.sql: |
{{ .Files.Get "migrations/004_api_grants.sql" | indent 4 }}

  005_plan_regression.sql: |
{{ .Files.Get "migrations/005_plan_regression.sql" | indent 4 }}

  006_oracle_targets.sql: |
{{ .Files.Get "migrations/006_oracle_targets.sql" | indent 4 }}

  007_cluster_engine.sql: |
{{ .Files.Get "migrations/007_cluster_engine.sql" | indent 4 }}
